### ISSUE TITLE
Missing a world for Materia

### ISSUE THREAD

**Issue by resech** [huntsffxiv/repo#1]
Thank you for adding Materia support, just wanted to point out that it looks like Sophia is missing from the world selection options:
![image](https://github.com/user-attachments/assets/2aff2c60-2893-4d92-ac8c-853f9ab9d380)

**Comment by huntsffxiv** [comment]
Thank you! I'll update this

**Comment by huntsffxiv** [comment]
I just released an update which should have that fixed

**Comment by resech** [comment]
Fixed
